<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pde_bsp_plugin"
 *
 * Auto generated by Extension Builder 2018-10-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PanadeEdu Beispiel Plugin',
    'description' => 'Rendert Beispiel Content ins Frontend',
    'category' => 'plugin',
    'author' => 'Christoph Beer',
    'author_email' => 'cbeer@schirra-it.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'extbase' => '8.7',
            'fluid' => '8.7',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
